loglevel: debug

bar:
  height: 18
  background: "#222222"
  foreground: "#ffffff"
  font:
    face: DejaVu Sans Mono
    size: 12

window:
  border: 3
  focused: "#1793D1"
  unfocused: "#222222"
  urgent: "#900000"
